### PR TITLE
Fix: Cannot read property 'aurelia' of null

### PR DESCRIPTION
**Pull request by obany**
Fixed bug causing Cannot read property 'aurelia' of null, when aurelia-app attribute was not immediately available.

### CODE REVIEW

**Comment by michaelbull** [comment]
For what it's worth, this issue was also identified by @niieani in [a recent PR](https://github.com/aurelia/protractor-plugin/pull/10#pullrequestreview-51624883).

**Comment by zewa666** [comment]
Good catch. Fix is fine :+1:

**Comment by niieani** [comment]
Fix is fine, but it only fixes one place where this can happen. @obany, would be great if you could also update the other 2 places where it might potentially break where we also do `document.querySelector("[aurelia-app]").aurelia`. Thanks!

**Comment by obany** [comment]
Updated the other 2 locations as well for extra guard, the only reason I didn't before was that the likelihood of them triggering was very low as you would have had to get passed the loadAndWaitForAureliaPage first.

**Review by niieani — APPROVED** [review]
Yeah, that's true. But still, better to have the fix applied everywhere :)

Thanks. Looks good.

**Pull request merged**
